#!/bin/bash
title="System Information Page $HOSTNAME"
current_time=$(date +"%x %r %z")
timestamp="Generated $current_time, by $USER"
cat << _EOF_
<HTML>
	<HEAD>
		<TITLE>$title</TITLE>
	</HEAD>
	<BODY>
		<H1>$title</H1>
		<p>$timestamp<p>
	</BODY>
</HTML>
_EOF_
